runtime: python312
entrypoint: gunicorn -b :$PORT app:app # This tells App Engine how to start your app
env_variables:
  FLASK_ENV: 'production' # Example environment variable

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto
